### ISSUE TITLE
Prettify error responses from graphql servers

### ISSUE THREAD

**Issue by martimatix** [dillonkearns/graphqelm#6]
Suppose a user installs graphqelm and runs the following:

`$ graphqelm https://api.github.com/graphql`

The above will get an error from the github graphql API server since the user did not submit an access token. Presently, the output for this case looks like this:

```
error { Error: GraphQL Error (Code: 401): {"response":{"message":"This endpoint requires you to be authenticated.","documentation_url":"https://developer.github.com/v3/#authentication","status":401},"request":{"query":"{\n    __schema {\n      queryType {\n        name\n      }\n      mutationType {\n        name\n      }\n      types {\n        ...FullType\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }"}}
    at GraphQLClient.<anonymous> (/Users/martimatix/.nvm/versions/node/v8.9.3/lib/node_modules/graphqelm/dist/bundle.js:12425:35)
    at step (/Users/martimatix/.nvm/versions/node/v8.9.3/lib/node_modules/graphqelm/dist/bundle.js:12378:23)
    at Object.next (/Users/martimatix/.nvm/versions/node/v8.9.3/lib/node_modules/graphqelm/dist/bundle.js:12359:53)
    at fulfilled (/Users/martimatix/.nvm/versions/node/v8.9.3/lib/node_modules/graphqelm/dist/bundle.js:12350:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  response:
   { message: 'This endpoint requires you to be authenticated.',
     documentation_url: 'https://developer.github.com/v3/#authentication',
     status: 401 },
  request:
   { query: '{\n    __schema {\n      queryType {\n        name\n      }\n      mutationType {\n        name\n      }\n      types {\n        ...FullType\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }',
     variables: undefined } }
```
Would it be possible to simply pretty print the response from the server?

**Comment by dillonkearns** [comment]
Great point! It looks pretty nice if I just print `err.response`:
<img width="786" alt="1__dillon_dillons-macbook-pro____src_graphqelm__zsh_" src="https://user-images.githubusercontent.com/1384166/34415937-0a3b37b2-eba6-11e7-8eb7-b1fcb50c9e87.png">

I pushed a change, I'll publish this with the next release. Thanks as always for the awesome feedback, Mario, I really appreciate it!

**Comment by martimatix** [comment]
Nice! Thanks for all your hard work, Dillon.

**Comment by dillonkearns** [comment]
My pleasure! I just published new package versions on npm and the elm package repository, including this change here.

Cheers,

Dillon
