### ISSUE TITLE
Issue with elm-format

### ISSUE THREAD

**Issue by martinos** [dillonkearns/graphqelm#62]
I tried to run graphqlelm with the on the github api using the following command:

```
graphqelm https://api.github.com/graphql --base Github --header 'Authorization: Bearer my_token
```

I have got the following error:

```
Fetching GraphQL schema...
Generating files...
/usr/local/lib/node_modules/graphqelm/dist/bundle.js:22286
    elmFormat.stdin.write(value);
                    ^

TypeError: Cannot read property 'write' of undefined
    at writeWithElmFormat (/usr/local/lib/node_modules/graphqelm/dist/bundle.js:22286:21)
    at Object.exports.writeFile (/usr/local/lib/node_modules/graphqelm/dist/bundle.js:22276:9)
    at Array.<anonymous> (/usr/local/lib/node_modules/graphqelm/dist/bundle.js:3842:31)
    at Function.onEffects [as func] (/usr/local/lib/node_modules/graphqelm/dist/bundle.js:7737:19)
    at A3 (/usr/local/lib/node_modules/graphqelm/dist/bundle.js:3970:11)
    at onMessage (/usr/local/lib/node_modules/graphqelm/dist/bundle.js:7520:12)
    at Object.callback (/usr/local/lib/node_modules/graphqelm/dist/bundle.js:7562:11)
    at step (/usr/local/lib/node_modules/graphqelm/dist/bundle.js:8099:32)
    at Timeout.work [as _onTimeout] (/usr/local/lib/node_modules/graphqelm/dist/bundle.js:8141:15)
    at ontimeout (timers.js:466:11)
```

Here is my elm-format version:

```
elm-format-0.18 0.6.1-alpha
```

And my graphqelm version

```
dillonkearns/graphqelm@11.1.0
```
My elm-format path:

```
/usr/local//bin/elm-format
```

Someone has in idea why I get this error message ?

**Comment by xtian** [comment]
@martinos Which version of Node are you using?

**Comment by Meroje** [comment]
It seems to be ulimit related, on macOS I solved it with help from this gist https://gist.github.com/tombigel/d503800a282fcadbee14b537735d202c (don't forget to reboot)

**Comment by dillonkearns** [comment]
@martinos it seems like this issue is resolved, but if not feel free to comment or reopen. Thanks!
